name: Test and lint

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.6'
            - name: Install dependencies
              run: python -m pip install -r python/requirements-dev.txt
            - name: Install honey package
              run: cd python && pip install -e .
            - name: Lint
              run: |
                  cd python
                  python -m pylint --disable=R,C src/
                  python -m pylint --disable=R,C tests/
            - name: Run black format check
              run: cd python && black --check .
            - name: Run pytest
              run: cd python && python -m pytest --cov=honey --cov-report html
            - name: Archive html coverage
              uses: actions/upload-artifact@v2
              with:
                  name: html-coverage
                  path: python/htmlcov

